name: Pull Request Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches: 
    - master
    - develop
    - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0
    - name: Send greeting
      run: ls -l && dotnet test Contoso.Tests/Contoso.Tests.csproj
